baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'apertus° (WIP)'
theme = "apertus"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[module]
# [[module.imports]]
# path = 'github.com/hugomods/bootstrap'

[[module.mounts]]
source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
target = "assets/js/bootstrap.bundle.min.js"

# [[module.mounts]]
# source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
# target = "assets/js/bootstrap.bundle.min.js"

# [[module.imports]]
# path = "github.com/hbstack/meta/recommended"

# [module]

# [[module.imports]]
# path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

# [[module.imports]]
# path = "github.com/apertus/apertus-theme"

[params]
dateFormat = "02 Jan 2006"
